"""add severity to alerts table

Revision ID: 7ca50af4c163
Revises: 94b2bbc07a3b
Create Date: 2026-06-13 10:49:55.955516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca50af4c163'
down_revision: Union[str, Sequence[str], None] = '94b2bbc07a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('severity', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'severity')
    # ### end Alembic commands ###
